---
title: "Data Cleaning, Descriptive Analysis and Correlation Measures"
output: github_document
---

```{r}
library(ggplot2)
library(readxl)
library(tidyverse)
library(arsenal)

```


```{r}
#located the data at the specified file path and stores the data in a variable called "data"
data <- read_excel("/Users/jaimerd/Desktop/master/Human Resources Analytics /data.xlsx")
```

```{r}
#summary of the data
summary(data)
```

Feature engineering

```{r}
#convert character (text) variables into factors
data <- data %>% mutate_if(is.character,as.factor)

#convert ordinal and categorical variables into factors
colums_factor <- c("Education", "EnvironmentSatisfaction", "JobInvolvement", "JobLevel", "JobSatisfaction", "PerformanceRating", "RelationshipSatisfaction", "StockOptionLevel", "WorkLifeBalance")
data[colums_factor] <- lapply(data[colums_factor], as.factor)
```

## Incorrect Data

```{r}

#department  
data <- data %>% 
  mutate(Department = recode(Department, 'HR' = 'Human Resources')) %>%
  mutate(Department = recode(Department, 'R & D' = "Research & Development"))
```

## Check for outliers

```{r}
#Age
boxplot(data$Age)
summary(data$Age)
data %>% count(Age>70) 
data %>% count(Age<18)
data$Age[data$Age > 70] <- NA
data$Age[data$Age < 10] <- NA

#Billable Rate
boxplot(data$BillableRate)

#Distance From Home 
boxplot(data$DistanceFromHome)

#Hourly pay rate
boxplot(data$HourlyPayRate)

#Monthly income
boxplot(data$MonthlyIncome)
summary(data$MonthlyIncome)

#Monthly rate
boxplot(data$MonthlyRate)

#Salary hike
boxplot(data$PercentSalaryHike)

#Years with current manager
table(data$YearsWithCurrManager)

#exclude ID, DOB and Over 18 variables because they are not going to have any implications in the model 
data <- data %>%  select(-ID)
data <- data %>%  select(-DOB)
data <-data %>% select(-Over18)

```

## Statistic summary and correlation analysis

ANOVA Test for numerical variables and Chi Squared Test for categotical Variables. Takin <0.01 as the reference value 

```{r}
my_controls <- tableby.control(
  test = T,
  total = FALSE,
  numeric.test = "anova", cat.test = "chisq",
  numeric.stats = c("meansd"),
  cat.stats = c("countpct"),
  )

descriptive_stats <- tableby(Attrition ~ .,
                             data = data,
                             control = my_controls)

summary(descriptive_stats, title = "Descriptive Statistic", text= TRUE)
```






